// Generated by CoffeeScript 1.7.1
(function() {
  var Board, Game, KifuPlayer, Koma, KomaType, MoveConvertor, SyogiJudgement, computeDuration, game, images, km1, km2, komaTypes, moveConvertor, util,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  util = {
    isVacant: function(val) {
      return val === null || val === void 0 || val === "" || val === 0;
    },
    isntVacant: function(val) {
      return val !== null && val !== void 0 && val !== "" && val !== 0;
    },
    reverseVector: function(position, playerNumber) {
      if (playerNumber === 1) {
        return position;
      }
      return {
        x: position.x * -1,
        y: position.y * -1,
        length: position.length
      };
    },
    posEq: function(p1, p2) {
      return p1.x === p2.x && p1.y === p2.y;
    },
    posAdd: function(p, v) {
      return {
        x: p.x + v.x,
        y: p.y + v.y,
        length: v.length
      };
    },
    posMul: function(p, times) {
      return {
        x: p.x * times,
        y: p.y * times,
        length: times
      };
    },
    posDup: function(p) {
      return {
        x: p.x,
        y: p.y,
        length: p.length
      };
    },
    posAdd1: function(p) {
      return {
        x: p.x + 1,
        y: p.y + 1,
        length: p.length
      };
    },
    posToStr: function(p) {
      return p.x + ":" + p.y;
    },
    isInRange: function(pos) {
      return 0 <= pos.x && pos.x < 9 && 0 <= pos.y && pos.y < 9;
    },
    allPos: function(predicate) {
      var x, y, _i, _results;
      _results = [];
      for (y = _i = 0; _i < 9; y = ++_i) {
        _results.push((function() {
          var _j, _results1;
          _results1 = [];
          for (x = _j = 0; _j < 9; x = ++_j) {
            _results1.push(predicate(x, y));
          }
          return _results1;
        })());
      }
      return _results;
    }
  };

  computeDuration = function(ms) {
    var h, m, s;
    if (ms < 0) {
      ms = 0;
    }
    h = String(Math.floor(ms / 3600000) + 100).substring(1);
    m = String(Math.floor((ms - h * 3600000) / 60000) + 100).substring(1);
    s = String(Math.round((ms - h * 3600000 - m * 60000) / 1000) + 100).substring(1);
    return m + ':' + s;
  };

  KomaType = (function() {
    function KomaType(id, name, nari, resourceId, nariId, moveDef, value) {
      this.id = id;
      this.name = name;
      this.nari = nari;
      this.resourceId = resourceId;
      this.nariId = nariId;
      this.moveDef = moveDef;
      this.value = value;
    }

    return KomaType;

  })();

  komaTypes = (function() {
    var setResource, _komaTypes;
    _komaTypes = {};
    setResource = function(id, name, nari, resourceId, nariId, moveDef, value) {
      return _komaTypes[id] = new KomaType(id, name, nari, resourceId, nariId, moveDef, value);
    };
    setResource("ou", "玉", false, "ou", "", {
      str: "12346789",
      moves: ["1", "2", "3", "4", "6", "7", "8", "9"]
    }, 9);
    setResource("ki", "金", false, "ki", "", {
      str: "123468",
      moves: ["1", "2", "3", "4", "6", "8"]
    }, 5);
    setResource("gi", "銀", true, "gi", "ng", {
      str: "12379",
      moves: ["1", "2", "3", "7", "9"]
    }, 4);
    setResource("ng", "成銀", false, "gi", "", {
      str: "123468",
      moves: ["1", "2", "3", "4", "6", "8"]
    }, 4);
    setResource("ke", "桂", true, "ke", "nk", {
      str: "ab",
      moves: ["a", "b"]
    }, 3);
    setResource("nk", "成桂", false, "ke", "", {
      str: "123468",
      moves: ["1", "2", "3", "4", "6", "8"]
    }, 3);
    setResource("ky", "香", true, "ky", "ny", {
      str: "2_",
      moves: ["2_"]
    }, 2);
    setResource("ny", "成香", false, "ky", "", {
      str: "123468",
      moves: ["1", "2", "3", "4", "6", "8"]
    }, 2);
    setResource("hi", "飛", true, "hi", "ry", {
      str: "2_4_6_8_",
      moves: ["2_", "4_", "6_", "8_"]
    }, 7);
    setResource("ry", "竜", false, "hi", "", {
      str: "12_34_6_78_9",
      moves: ["1", "2_", "3", "4_", "6_", "7", "8_", "9"]
    }, 7);
    setResource("ka", "角", true, "ka", "um", {
      str: "1_3_7_9_",
      moves: ["1_", "3_", "7_", "9_"]
    }, 6);
    setResource("um", "馬", false, "ka", "", {
      str: "1_23_467_89_",
      moves: ["1_", "2", "3_", "4", "6", "7_", "8", "9_"]
    }, 6);
    setResource("hu", "歩", true, "hu", "to", {
      str: "2",
      moves: ["2"]
    }, 1);
    setResource("to", "と", false, "hu", "", {
      str: "123468",
      moves: ["1", "2", "3", "4", "6", "8"]
    }, 1);
    return _komaTypes;
  })();

  images = {
    koma1: {
      "ou": "sgl01.png",
      "hi": "sgl02.png",
      "ka": "sgl03.png",
      "ki": "sgl04.png",
      "gi": "sgl05.png",
      "ke": "sgl06.png",
      "ky": "sgl07.png",
      "hu": "sgl08.png",
      "ry": "sgl12.png",
      "um": "sgl13.png",
      "ng": "sgl15.png",
      "nk": "sgl16.png",
      "ny": "sgl17.png",
      "to": "sgl18.png"
    },
    koma2: {
      "ou": "sgl31.png",
      "hi": "sgl32.png",
      "ka": "sgl33.png",
      "ki": "sgl34.png",
      "gi": "sgl35.png",
      "ke": "sgl36.png",
      "ky": "sgl37.png",
      "hu": "sgl38.png",
      "ry": "sgl42.png",
      "um": "sgl43.png",
      "ng": "sgl45.png",
      "nk": "sgl46.png",
      "ny": "sgl47.png",
      "to": "sgl48.png"
    }
  };

  MoveConvertor = (function() {
    function MoveConvertor() {
      var create8Aray, cutLength;
      create8Aray = function(v) {
        return _([1, 2, 3, 4, 5, 6, 7, 8]).map(function(i) {
          return util.posMul(v, i);
        });
      };
      this.moveDef = [
        [
          "1", [
            {
              x: 1,
              y: -1,
              length: 1
            }
          ]
        ], [
          "2", [
            {
              x: 0,
              y: -1,
              length: 1
            }
          ]
        ], [
          "3", [
            {
              x: -1,
              y: -1,
              length: 1
            }
          ]
        ], [
          "4", [
            {
              x: 1,
              y: 0,
              length: 1
            }
          ]
        ], [
          "6", [
            {
              x: -1,
              y: 0,
              length: 1
            }
          ]
        ], [
          "7", [
            {
              x: 1,
              y: 1,
              length: 1
            }
          ]
        ], [
          "8", [
            {
              x: 0,
              y: 1,
              length: 1
            }
          ]
        ], [
          "9", [
            {
              x: -1,
              y: 1,
              length: 1
            }
          ]
        ], [
          "a", [
            {
              x: 1,
              y: -2,
              length: 1
            }
          ]
        ], [
          "b", [
            {
              x: -1,
              y: -2,
              length: 1
            }
          ]
        ], [
          "1_", create8Aray({
            x: 1,
            y: -1
          })
        ], [
          "2_", create8Aray({
            x: 0,
            y: -1
          })
        ], [
          "3_", create8Aray({
            x: -1,
            y: -1
          })
        ], [
          "4_", create8Aray({
            x: 1,
            y: 0
          })
        ], [
          "6_", create8Aray({
            x: -1,
            y: 0
          })
        ], [
          "7_", create8Aray({
            x: 1,
            y: 1
          })
        ], [
          "8_", create8Aray({
            x: 0,
            y: 1
          })
        ], [
          "9_", create8Aray({
            x: -1,
            y: 1
          })
        ]
      ];
      this.moveDef1 = {};
      this.moveDef2 = {};
      _(this.moveDef).each((function(_this) {
        return function(pair) {
          _this.moveDef1[pair[0]] = pair[1];
          return _this.moveDef2[pair[0]] = _(pair[1]).map(function(v) {
            return util.reverseVector(v, 2);
          });
        };
      })(this));
      this.moveKeysShort = {
        "1": true,
        "2": true,
        "3": true,
        "4": true,
        "6": true,
        "7": true,
        "8": true,
        "9": true,
        "a": true,
        "b": true
      };
      this.moveKeysLong = {
        "1_": true,
        "2_": true,
        "3_": true,
        "4_": true,
        "6_": true,
        "7_": true,
        "8_": true,
        "9_": true
      };
      cutLength = function(playerNumber, positions, gameBoard) {
        var ngLength, ngPos, toKoma;
        ngLength = 0;
        ngPos = _(positions).find(function(pos) {
          return util.isntVacant(gameBoard.getKoma(pos));
        });
        if (ngPos) {
          toKoma = gameBoard.getKoma(ngPos);
          ngLength = toKoma.playerNumber === playerNumber ? ngPos.length : ngPos.length + 1;
        }
        if (ngLength !== 0) {
          return _(positions).filter(function(pos) {
            return pos.length < ngLength;
          });
        } else {
          return positions;
        }
      };
      this.getMovablePos = function(playerNumber, komaType, position, gameBoard) {
        var moves, result, _moveDef;
        moves = komaTypes[komaType].moveDef.moves;
        _moveDef = playerNumber === 1 ? this.moveDef1 : this.moveDef2;
        result = [];
        _(moves).each(function(move) {
          var positions;
          positions = _(_moveDef[move]).map(function(v) {
            return util.posAdd(position, v);
          });
          positions = _(positions).filter(function(pos) {
            return util.isInRange(pos);
          });
          positions = cutLength(playerNumber, positions, gameBoard);
          return result = result.concat(positions);
        });
        return result;
      };
      this.getPutableCell = function(playerNumber, komaType, gameBoard) {
        var filter, positions;
        positions = [];
        util.allPos(function(x, y) {
          if (util.isVacant(gameBoard.getKoma({
            x: x,
            y: y
          }))) {
            return positions.push({
              x: x,
              y: y
            });
          }
        });
        if (komaType === "hu" || komaType === "ky") {
          filter = playerNumber === 1 ? function(p) {
            return p.y !== 0;
          } : function(p) {
            return p.y !== 8;
          };
        }
        if (komaType === "ke") {
          filter = playerNumber === 1 ? function(p) {
            return p.y > 1;
          } : function(p) {
            return p.y < 7;
          };
        }
        if (filter) {
          return _(positions).filter(filter);
        } else {
          return positions;
        }
      };
      this.getNari = function(playerNumber, komaType, fromPos, toPos) {
        if (komaTypes[komaType].nari === false) {
          return "none";
        }
        if (playerNumber === 1) {
          if (fromPos.y < 3 || toPos.y < 3) {
            if ((komaType === "hu" || komaType === "ky") && toPos.y === 0) {
              return "force";
            }
            if (komaType === "ke" && toPos.y < 2) {
              return "force";
            }
            return "possible";
          } else {
            return "none";
          }
        } else {
          if (fromPos.y > 5 || toPos.y > 5) {
            if ((komaType === "hu" || komaType === "ky") && toPos.y === 8) {
              return "force";
            }
            if (komaType === "ke" && toPos.y > 6) {
              return "force";
            }
            return "possible";
          } else {
            return "none";
          }
        }
      };
    }

    return MoveConvertor;

  })();

  moveConvertor = new MoveConvertor();

  Koma = (function() {
    function Koma(playerNumber, komaType) {
      this.playerNumber = playerNumber;
      this.komaType = komaType;
    }

    return Koma;

  })();

  km1 = function(komaType) {
    return new Koma(1, komaType);
  };

  km2 = function(komaType) {
    return new Koma(2, komaType);
  };

  Board = (function() {
    function Board() {
      this.getOu = __bind(this.getOu, this);
      this.getPlayerKoma = __bind(this.getPlayerKoma, this);
      this.getKomaWithPosition = __bind(this.getKomaWithPosition, this);
      this.removeKomaFromKomadai = __bind(this.removeKomaFromKomadai, this);
      this.removeKoma = __bind(this.removeKoma, this);
      this.putKoma = __bind(this.putKoma, this);
      this.duplicate = __bind(this.duplicate, this);
      this.player1 = {
        life: 9,
        time: 600000
      };
      this.player2 = {
        life: 9,
        time: 600000
      };
      this.komaDai = [[], []];
      this.board = [[], [], [], [], [], [], [], [], []];
      this.life = [9, 9];
    }

    Board.prototype.clearBoard = function() {
      return this.board = [[], [], [], [], [], [], [], [], []];
    };

    Board.prototype.initBoard = function(playerNumber) {
      if (playerNumber === 1) {
        return this.board = [['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], [km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu')], ['', km1('hi'), '', '', '', '', '', km1('ka'), ''], [km1('ky'), km1('ke'), km1('gi'), km1('ki'), km1('ou'), km1('ki'), km1('gi'), km1('ke'), km1('ky')]];
      } else if (playerNumber === 2) {
        return this.board = [[km2('ky'), km2('ke'), km2('gi'), km2('ki'), km2('ou'), km2('ki'), km2('gi'), km2('ke'), km2('ky')], ['', km2('ka'), '', '', '', '', '', km2('hi'), ''], [km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu')], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '']];
      } else {
        return this.board = [[km2('ky'), km2('ke'), km2('gi'), km2('ki'), km2('ou'), km2('ki'), km2('gi'), km2('ke'), km2('ky')], ['', km2('ka'), '', '', '', '', '', km2('hi'), ''], [km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu'), km2('hu')], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', ''], [km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu'), km1('hu')], ['', km1('hi'), '', '', '', '', '', km1('ka'), ''], [km1('ky'), km1('ke'), km1('gi'), km1('ki'), km1('ou'), km1('ki'), km1('gi'), km1('ke'), km1('ky')]];
      }
    };

    Board.prototype.duplicate = function() {
      var board, x, y, _i, _j;
      board = new Board();
      for (y = _i = 0; _i < 9; y = ++_i) {
        for (x = _j = 0; _j < 9; x = ++_j) {
          if (this.board[x][y]) {
            board.board[x][y] = new Koma(this.board[x][y].playerNumber, this.board[x][y].komaType);
          } else {
            board.board[x][y] = '';
          }
        }
      }
      board.komaDai[0] = board.komaDai[0].concat(this.komaDai[0]);
      board.komaDai[1] = board.komaDai[1].concat(this.komaDai[1]);
      board.life[0] = this.life[0];
      board.life[1] = this.life[1];
      return board;
    };

    Board.prototype.getKoma = function(position) {
      var e;
      try {
        return this.board[position.y][position.x];
      } catch (_error) {
        e = _error;
        console.log("get:" + position.x + ", " + position.y);
        throw e;
      }
    };

    Board.prototype.getExistsHuColumn = function(playerNumber) {
      var koma, result, x, y, _i, _j;
      result = {};
      for (y = _i = 0; _i < 9; y = ++_i) {
        for (x = _j = 0; _j < 9; x = ++_j) {
          koma = this.board[y][x];
          if (koma && koma.playerNumber === playerNumber && koma.komaType === "hu") {
            result[x] = true;
          }
        }
      }
      console.log(result);
      return result;
    };

    Board.prototype.putKoma = function(koma, position) {
      return this.board[position.y][position.x] = koma;
    };

    Board.prototype.removeKoma = function(position) {
      return this.board[position.y][position.x] = void 0;
    };

    Board.prototype.getKomaFromKomadai = function(playerNumber, komaType) {
      var find, index, koma;
      find = false;
      console.log(komaType);
      index = playerNumber === 1 ? 0 : 1;
      koma = _(this.komaDai[index]).find(function(koma) {
        return koma.komaType === komaType;
      });
      this.komaDai[index] = _(this.komaDai[index]).filter(function(koma) {
        if (find) {
          return true;
        }
        if (koma.komaType === komaType) {
          return !(find = true);
        }
        return true;
      });
      return koma;
    };

    Board.prototype.putKomaToKomadai = function(playerNumber, koma) {
      var type;
      console.log("putKomaToKomadai");
      koma = new Koma(koma.playerNumber, koma.komaType);
      koma.playerNumber = playerNumber;
      type = komaTypes[koma.komaType];
      console.log(type);
      koma.komaType = komaTypes[koma.komaType].resourceId;
      if (playerNumber === 1) {
        this.komaDai[0].push(koma);
        return this.komaDai[0] = _(this.komaDai[0]).sortBy(function(koma) {
          return komaTypes[koma.komaType].value;
        });
      } else {
        this.komaDai[1].push(koma);
        return this.komaDai[1] = _(this.komaDai[1]).sortBy(function(koma) {
          return komaTypes[koma.komaType].value;
        });
      }
    };

    Board.prototype.removeKomaFromKomadai = function(playerNumber, komaType) {
      var find, index, koma;
      console.log("removeKomaFromKomadai : " + playerNumber + " : " + komaType);
      find = false;
      index = playerNumber === 1 ? 0 : 1;
      koma = _(this.komaDai[index]).find(function(koma) {
        return koma.komaType === komaType;
      });
      this.komaDai[index] = _(this.komaDai[index]).filter(function(koma) {
        if (find) {
          return true;
        }
        if (koma.komaType === komaType) {
          return !(find = true);
        }
        return true;
      });
      return koma;
    };

    Board.prototype.getKomaWithPosition = function(predicate) {
      var koma, result, x, y, _i, _j;
      result = [];
      for (y = _i = 0; _i < 9; y = ++_i) {
        for (x = _j = 0; _j < 9; x = ++_j) {
          koma = this.board[y][x];
          if (koma && predicate(koma)) {
            result.push({
              koma: koma,
              position: {
                x: x,
                y: y
              }
            });
          }
        }
      }
      return result;
    };

    Board.prototype.getPlayerKoma = function(playerNumber) {
      return this.getKomaWithPosition(function(koma) {
        return koma.playerNumber === playerNumber;
      });
    };

    Board.prototype.getOu = function(playerNumber) {
      var ou;
      ou = this.getKomaWithPosition(function(koma) {
        return koma.playerNumber === playerNumber && koma.komaType === "ou";
      });
      console.log("ouNum:" + ou.length);
      if (ou[0]) {
        return ou[0];
      } else {
        return null;
      }
    };

    return Board;

  })();

  Game = (function() {
    function Game(playerNumber) {
      this.playerNumber = playerNumber;
      this.getCurrentPlayer = __bind(this.getCurrentPlayer, this);
      this.canPutKoma = __bind(this.canPutKoma, this);
      this.putKoma = __bind(this.putKoma, this);
      this.canMoveKoma = __bind(this.canMoveKoma, this);
      this.moveKoma = __bind(this.moveKoma, this);
      this.start = __bind(this.start, this);
      this.getPlayerInfoCommand = __bind(this.getPlayerInfoCommand, this);
      this.board = new Board();
      this.board.initBoard(this.playerNumber);
      this.judge = new SyogiJudgement();
      this.updateGameInfo = function() {};
    }

    Game.prototype.getPlayerInfoCommand = function() {
      return {
        method: "adjustTime",
        player1: this.board.player1,
        player2: this.board.player2
      };
    };

    Game.prototype.start = function() {
      var updateTimer;
      this.turn = 1;
      this.state = "playing";
      this.currentTime = Date.now();
      updateTimer = (function(_this) {
        return function() {
          var oldTime, player;
          if (_this.state !== "playing") {
            return;
          }
          oldTime = _this.currentTime;
          _this.currentTime = Date.now();
          player = _this.getCurrentPlayer();
          player.time -= _this.currentTime - oldTime;
          graphicApi.updateGameInfo(_this.getPlayerInfoCommand());
          if (player.time < 0) {
            socket.emit('game', {
              method: "timeout",
              playerNumber: 2 - _this.turn % 2
            });
          }
          return window.setTimeout(updateTimer, 500);
        };
      })(this);
      return updateTimer();
    };

    Game.prototype.isPlayerTurn = function() {
      return 2 - this.turn % 2 === this.playerNumber;
    };

    Game.prototype.nextTurn = function() {
      return this.turn++;
    };

    Game.prototype.setGameInfoUpdater = function(updater) {
      return this.updateGameInfo = updater;
    };

    Game.prototype.end = function() {
      console.log("end game");
      return this.state = "end";
    };

    Game.prototype.moveKoma = function(moveInfo, check) {
      var bkBoard, fromKoma, putKoma, toKoma;
      bkBoard = this.board.duplicate();
      this.board.getKoma(moveInfo.to.position);
      fromKoma = this.board.getKoma(moveInfo.from.position);
      toKoma = this.board.getKoma(moveInfo.to.position);
      if (util.isntVacant(toKoma)) {
        this.board.putKomaToKomadai(2 - this.turn % 2, toKoma);
      }
      this.board.removeKoma(moveInfo.from.position);
      putKoma = new Koma(fromKoma.playerNumber, fromKoma.komaType);
      putKoma.komaType = moveInfo.to.komaType;
      this.board.putKoma(putKoma, moveInfo.to.position);
      if (this.judge.isOute(this, 2 - this.turn % 2)) {
        console.log("王手無視");
        this.board = bkBoard;
        return false;
      }
      if (this.judge.isOute(this, 2 - this.turn % 2)) {
        console.log("oute");
      }
      if (check) {
        this.board = bkBoard;
      } else {
        this.turn++;
      }
      return true;
    };

    Game.prototype.canMoveKoma = function(moveInfo) {
      return this.moveKoma(moveInfo, true);
    };

    Game.prototype.putKoma = function(moveInfo, check) {
      var bkBoard, fromKoma;
      bkBoard = this.board.duplicate();
      fromKoma = this.board.getKomaFromKomadai(2 - this.turn % 2, moveInfo.to.komaType);
      this.board.putKoma(fromKoma, moveInfo.to.position);
      if (this.judge.isOute(this, 2 - this.turn % 2)) {
        console.log("王手無視");
        this.board = bkBoard;
        return false;
      }
      if (check) {
        this.board = bkBoard;
      } else {
        this.turn++;
      }
      return true;
    };

    Game.prototype.canPutKoma = function(moveInfo) {
      return this.putKoma(moveInfo, true);
    };

    Game.prototype.isTsumi = function() {
      return this.judge.isTsumi(this, 2 - this.turn % 2);
    };

    Game.prototype.getCurrentPlayer = function() {
      if (this.turn % 2 === 1) {
        return this.board.player1;
      } else {
        return this.board.player2;
      }
    };

    return Game;

  })();

  KifuPlayer = (function() {
    function KifuPlayer(kifu, playerNumber, refresh) {
      var currentBoard;
      this.kifu = kifu;
      this.playerNumber = playerNumber;
      this.refresh = refresh;
      this.getPlayerInfo = __bind(this.getPlayerInfo, this);
      this.index = 0;
      this.currentTime = Date.now();
      this.board = new Board();
      this.board.initBoard();
      this.boards = [];
      this.elapsedTime = 0;
      currentBoard = this.board;
      this.boards.push(this.board);
      _(this.kifu).each((function(_this) {
        return function(te) {
          return _this.readTe(te);
        };
      })(this));
    }

    KifuPlayer.prototype.getPlayerInfo = function() {
      var board, player1, player2;
      board = this.boards[this.boards.length - 1];
      if (this.currentPlayerNumber === 1) {
        player1 = {
          life: board.player1.life,
          time: board.player1.time + this.currentTime - Date.now() - this.elapsedTime
        };
        player2 = board.player2;
      } else {
        player1 = board.player1;
        player2 = {
          life: board.player2.life,
          time: board.player2.time + this.currentTime - Date.now() - this.elapsedTime
        };
      }
      return {
        player1: player1,
        player2: player2
      };
    };

    KifuPlayer.prototype.getCurrentBoard = function() {
      return this.boards[this.index];
    };

    KifuPlayer.prototype.addKifu = function(te) {
      return this.readTe(te);
    };

    KifuPlayer.prototype.readTe = function(te) {
      var currentBoard, currentPlayerNumber, toKoma;
      currentBoard = this.boards[this.boards.length - 1];
      currentBoard = currentBoard.duplicate();
      currentPlayerNumber = 2 - te.turn % 2;
      currentBoard.player1 = te.playerInfo.player1;
      currentBoard.player2 = te.playerInfo.player2;
      this.currentTime = Date.now();
      currentBoard.turn = te.turn;
      if (te.info.type === "moveKoma") {
        if (!te.foul) {
          if (te.info.from.x !== -1) {
            currentBoard.removeKoma(te.info.from);
            toKoma = currentBoard.getKoma(te.info.to);
          } else {
            currentBoard.removeKomaFromKomadai(currentPlayerNumber, te.info.koma);
          }
          if (toKoma) {
            currentBoard.removeKoma(te.info.to);
            currentBoard.putKomaToKomadai(currentPlayerNumber, new Koma(currentPlayerNumber, toKoma.komaType));
          }
          currentBoard.putKoma(new Koma(currentPlayerNumber, te.info.koma), te.info.to);
          currentBoard.emphasisPosition = te.info.to;
          this.currentPlayerNumber = 2 - (te.turn + 1) % 2;
        } else {
          currentBoard.life[currentPlayerNumber] = currentBoard.life[currentPlayerNumber] - 1;
          this.currentPlayerNumber = 2 - te.turn % 2;
        }
      } else if (te.info.type === "endGame") {
        currentBoard.endGame = true;
      }
      return this.boards.push(currentBoard);
    };

    KifuPlayer.prototype.toStart = function() {
      if (this.index !== 0) {
        this.index = 0;
        return this.refresh(this.index, this.boards[this.index]);
      }
    };

    KifuPlayer.prototype.next = function() {
      this.index++;
      this.refresh(this.index, this.boards[this.index]);
      return this.activateUpdateTimer();
    };

    KifuPlayer.prototype.back = function() {
      this.index--;
      return this.refresh(this.index, this.boards[this.index]);
    };

    KifuPlayer.prototype.toEnd = function() {
      if (this.index !== this.boards.length - 1) {
        this.index = this.boards.length - 1;
        this.refresh(this.index, this.boards[this.index]);
        return this.activateUpdateTimer();
      }
    };

    KifuPlayer.prototype.toIndex = function(index) {
      if (this.index !== index) {
        this.index = index;
        this.boards[index];
        this.refresh(this.index, this.boards[this.index]);
        if (this.index === this.boards.length - 1) {
          return this.activateUpdateTimer();
        }
      }
    };

    KifuPlayer.prototype.activateUpdateTimer = function() {
      var updateTimer;
      updateTimer = (function(_this) {
        return function() {
          if (_this.index !== _this.boards.length - 1) {
            return;
          }
          if (_this.boards[_this.boards.length - 1].endGame) {
            return;
          }
          if (kifuApi.state !== "replay") {
            return;
          }
          graphicApi.updateGameInfo(_this.getPlayerInfo());
          return window.setTimeout(updateTimer, 500);
        };
      })(this);
      return updateTimer();
    };

    return KifuPlayer;

  })();

  SyogiJudgement = (function() {
    var canMove;

    function SyogiJudgement() {
      this.isTsumi = __bind(this.isTsumi, this);
      this.isOute = __bind(this.isOute, this);
    }

    canMove = function(game, playerNumber, moveInfo) {
      var fromKoma, pos, toKoma, toKomaType;
      if (game.state !== "playing") {
        return false;
      }
      if (game.turn % 2 !== playerNumber % 2) {
        return false;
      }
      fromKoma = game.board.getKoma(moveInfo.from.position);
      toKomaType = komaTypes[moveInfo.to.komaType];
      if (util.isInRange(moveInfo.from.position) || util.isInRange(moveInfo.to.position)) {
        return false;
      }
      if (!fromKoma) {
        return false;
      }
      if (fromKoma.komaType.name !== moveInfo.from.komaType) {
        return false;
      }
      if (toKomaType.name !== fromKoma.komaType.name && toKomaType.resourceId !== fromKoma.komaType.name) {
        return false;
      }
      toKoma = game.board.getKoma(moveInfo.to.position);
      if (toKoma && toKoma.playerNumber === playerNumber) {
        return false;
      }
      pos = _(moveConvertor.getMovablePos(playerNumber, moveInfo.from.komaType, moveInfo.from.position)).find(function(pos) {
        return util.posEq(pos, moveInfo.to.position);
      });
      if (pos) {
        return true;
      }
      return false;
    };

    SyogiJudgement.prototype.isOute = function(game, playerNumber) {
      var enemyPlayerNumber, kikiMap, ou, ouPos;
      kikiMap = {};
      enemyPlayerNumber = playerNumber === 1 ? 2 : 1;
      _(game.board.getPlayerKoma(enemyPlayerNumber)).each(function(komaInfo) {
        var postions;
        postions = _(moveConvertor.getMovablePos(enemyPlayerNumber, komaInfo.koma.komaType, komaInfo.position, game.board));
        postions = _(postions).map(function(pos) {
          return util.posToStr(pos);
        });
        return _(postions).each(function(p) {
          return kikiMap[p] = true;
        });
      });
      ou = game.board.getOu(playerNumber);
      ouPos = util.posToStr(ou.position);
      console.log("playerNumber:" + playerNumber);
      console.log("ouPos:" + ouPos);
      console.log(kikiMap);
      if (kikiMap[ouPos]) {
        return true;
      } else {
        return false;
      }
    };

    SyogiJudgement.prototype.isTsumi = function(game, playerNumber) {
      return _(game.board.getPlayerKoma(playerNumber)).some(function(komaInfo) {
        var positions;
        positions = moveConvertor.getMovablePos(playerNumber, komaInfo.koma.komaType, komaInfo.position, game.board);
        return _(positions).some(function(pos) {
          var moveInfo;
          moveInfo = {
            from: {
              position: komaInfo.position,
              komaType: komaInfo.koma.komaType
            },
            to: {
              position: pos,
              komaType: komaInfo.koma.komaType
            }
          };
          return game.canMoveKoma(moveInfo);
        });
      });
    };

    return SyogiJudgement;

  })();

  game = null;

  gameApi.startGame = function(playerNumber) {
    graphicApi.clearTable();
    game = new Game(playerNumber);
    game.start();
    gameApi.game = game;
    return graphicApi.redrawKoma(game.board, game.state, game.turn);
  };

  gameApi.endGame = function(info) {
    game.end();
    return graphicApi.redrawKoma(game.board, game.state, game.turn);
  };

  gameApi.tryMoveKoma = function(moveInfo) {
    return socket.emit('game', {
      method: "moveKoma",
      args: moveInfo
    });
  };

  gameApi.moveKoma = function(moveInfo) {
    game.moveKoma(moveInfo);
    return graphicApi.redrawKoma(game.board, game.state, game.turn);
  };

  gameApi.tryPutKoma = function(moveInfo) {
    return socket.emit('game', {
      method: "putKoma",
      args: moveInfo
    });
  };

  gameApi.doCommand = function(commands) {
    var bkInvated, isFoul;
    console.log("do command");
    isFoul = false;
    bkInvated = graphicApi.invatedPosition;
    graphicApi.invatedPosition = null;
    _(commands).each(function(command) {
      console.log(command);
      if (command.method === "removeKomaFromKomadai") {
        return game.board.removeKomaFromKomadai(command.playerNumber, command.koma.komaType);
      } else if (command.method === "putKomaToKomadai") {
        return game.board.putKomaToKomadai(command.playerNumber, command.koma);
      } else if (command.method === "removeKoma") {
        game.board.removeKoma(command.position);
        return graphicApi.invatedPosition = command.position;
      } else if (command.method === "putKoma") {
        game.board.putKoma(command.koma, command.position);
        return graphicApi.invatedPosition = command.position;
      } else if (command.method === "adjustTime") {
        game.board.player1.time = command.player1.time;
        game.board.player2.time = command.player2.time;
        return graphicApi.updateGameInfo(command);
      } else if (command.method === "foul") {
        game.getCurrentPlayer().life--;
        graphicApi.updateGameInfo(game.getPlayerInfoCommand());
        return isFoul = true;
      }
    });
    if (isFoul) {
      graphicApi.initializeTableState();
      graphicApi.invatedPosition = bkInvated;
    } else {
      game.nextTurn();
    }
    return graphicApi.redrawKoma(game.board, game.state, game.turn);
  };

  gameApi.putKoma = function(moveInfo) {
    console.log("put koma");
    game.putKoma(moveInfo);
    return graphicApi.redrawKoma(game.board, game.state, game.turn);
  };

  graphicApi.updateGameInfo = function(command) {
    $("#gameInfo1").html("");
    $("#gameInfo2").html("");
    graphicApi.getGameInfoDiv(1).html("▲ 時間：" + computeDuration(command.player1.time) + " &nbsp;&nbsp;&nbsp;反則：" + command.player1.life);
    return graphicApi.getGameInfoDiv(2).html("△ 時間：" + computeDuration(command.player2.time) + " &nbsp;&nbsp;&nbsp;反則：" + command.player2.life);
  };

  graphicApi.redrawKoma = function(board, state, turn) {
    var $board, image, koma, komadai1, komadai2, td, tmp, x, xx, y, yy, _i, _results;
    $board = $('#board');
    komadai1 = graphicApi.getKomaDai(1);
    komadai2 = graphicApi.getKomaDai(2);
    graphicApi.initializeTableState();
    graphicApi.clearKoma();
    tmp = "";
    _(board.komaDai[0]).each(function(koma) {
      var image;
      image = graphicApi.getKomaImage(koma);
      if (tmp === koma.komaType) {
        image.css({
          "margin-left": "-50px"
        });
      }
      tmp = koma.komaType;
      if (turn % 2 === koma.playerNumber % 2 && state === "playing") {
        (function(komaType) {
          return image.bind("click", function() {
            return graphicApi.showPutableCell(1, komaType, board);
          });
        })(tmp);
      }
      return komadai1.append(image);
    });
    tmp = "";
    _(board.komaDai[1]).each(function(koma) {
      var image;
      image = graphicApi.getKomaImage(koma);
      if (tmp === koma.komaType) {
        image.css({
          "margin-left": "-50px"
        });
      }
      tmp = koma.komaType;
      if (turn % 2 === koma.playerNumber % 2 && state === "playing") {
        (function(komaType) {
          return image.bind("click", function() {
            return graphicApi.showPutableCell(2, komaType, board);
          });
        })(tmp);
      }
      return komadai2.append(image);
    });
    _results = [];
    for (y = _i = 0; _i < 9; y = ++_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (x = _j = 0; _j < 9; x = ++_j) {
          xx = "" + (9 - x);
          yy = "" + (y + 1);
          td = graphicApi.getCell(xx, yy);
          koma = board.getKoma({
            x: xx - 1,
            y: yy - 1
          });
          if (koma) {
            image = graphicApi.getKomaImage(koma);
            if (turn % 2 === koma.playerNumber % 2 && state === "playing") {
              (function(pos) {
                return image.bind("click", function() {
                  return graphicApi.showMovableCell(pos, board);
                });
              })({
                x: xx - 1,
                y: yy - 1
              });
            }
            _results1.push(td.append(image));
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

  graphicApi.drawKomaDaiKoma = function(playerNumber, komaList) {
    var komadai, tmp;
    komadai = graphicApi.getKomaDai(playerNumber);
    tmp = "";
    return _(komaList).each(function(koma) {
      var image;
      image = graphicApi.getKomaImage(koma);
      if (tmp === koma.komaType) {
        image.css({
          "margin-left": "-50px"
        });
      }
      tmp = koma.komaType;
      if (game.turn % 2 === koma.playerNumber % 2) {
        (function(komaType) {
          return image.bind("click", function() {
            return graphicApi.showPutableCell(1, komaType, game.board);
          });
        })(tmp);
      }
      return komadai.append(image);
    });
  };

  graphicApi.showMovableCell = function(fromPos, gameBoard) {
    var koma, positions, td;
    console.log("show movable");
    graphicApi.initializeTableState();
    koma = gameBoard.getKoma(fromPos);
    td = graphicApi.getCell(fromPos.x + 1, fromPos.y + 1);
    td.css({
      "background-color": "rgba(256,150,150,0.5)"
    });
    console.log("get movable");
    positions = moveConvertor.getMovablePos(koma.playerNumber, koma.komaType, fromPos, gameBoard);
    return _(positions).each(function(pos) {
      td = graphicApi.getCell(pos.x + 1, pos.y + 1);
      td.css({
        "background-color": "rgba(256,150,150,0.5)"
      });
      return (function() {
        var fromKoma, moveInfo, toPos;
        fromPos = util.posDup(fromPos);
        toPos = util.posDup(pos);
        fromKoma = gameBoard.getKoma(fromPos);
        moveInfo = {
          from: {
            position: fromPos,
            komaType: fromKoma.komaType
          },
          to: {
            position: toPos,
            komaType: fromKoma.komaType
          }
        };
        return td.bind("click", function() {
          var nari;
          nari = moveConvertor.getNari(koma.playerNumber, koma.komaType, moveInfo.from.position, moveInfo.to.position);
          if (nari === "force") {
            moveInfo.to.komaType = komaTypes[moveInfo.to.komaType].nariId;
          } else if (nari === "possible") {
            $("#nariDiv").show();
            $("#modal-overlay").show();
            $("#nariDiv").css({
              "background-color": "#FFFFFF",
              "opacity": 0
            });
            $("#modal-overlay").css({
              "background-color": "#000000",
              "opacity": 0
            });
            $("#nariDiv").animate({
              "background-color": "#FFFFFF",
              "opacity": 0.95
            }, 120);
            $("#modal-overlay").animate({
              "background-color": "#000000",
              "opacity": 0.3
            }, 120);
            graphicApi.nari = function(nari) {
              $("#modal-overlay").hide();
              $("#nariDiv").hide();
              if (nari) {
                moveInfo.to.komaType = komaTypes[moveInfo.to.komaType].nariId;
              }
              return gameApi.tryMoveKoma(moveInfo);
            };
            return;
          }
          return gameApi.tryMoveKoma(moveInfo);
        });
      })();
    });
  };

  graphicApi.showPutableCell = function(playerNumber, komaType, gameBoard) {
    var columns, positions;
    console.log("showPutableCell");
    graphicApi.initializeTableState();
    positions = moveConvertor.getPutableCell(playerNumber, komaType, gameBoard);
    if (komaType === "hu") {
      columns = gameBoard.getExistsHuColumn(playerNumber);
      positions = _(positions).filter(function(p) {
        if (columns[p.x]) {
          return false;
        } else {
          return true;
        }
      });
    }
    return _(positions).each(function(pos) {
      var td;
      td = graphicApi.getCell(pos.x + 1, pos.y + 1);
      td.css({
        "background-color": "rgba(256,150,150,0.5)"
      });
      return (function() {
        var moveInfo;
        moveInfo = {
          to: {
            position: pos,
            komaType: komaType
          }
        };
        return td.bind("click", function() {
          return gameApi.tryPutKoma(moveInfo);
        });
      })();
    });
  };

  graphicApi.clearTable = function() {
    var board, cell, row, x, xx, y, yy, _i, _results;
    graphicApi.invatedPosition = null;
    board = $('#board');
    board.html("");
    _results = [];
    for (y = _i = 0; _i < 9; y = ++_i) {
      yy = "" + (y + 1);
      row = $("<div id='row_" + yy + "'></div>");
      board.append(row);
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (x = _j = 0; _j < 9; x = ++_j) {
          xx = "" + (9 - x);
          cell = $("<div id='cell_" + xx + "_" + yy + "' class='cell'></div>").offset({
            top: y * 64,
            left: x * 60
          });
          _results1.push(row.append(cell));
        }
        return _results1;
      })());
    }
    return _results;
  };

  graphicApi.clearKoma = function() {
    var allKoma;
    allKoma = $(".koma");
    allKoma.unbind("click");
    return allKoma.remove();
  };

  graphicApi.initializeTableState = function() {
    var allTd, td;
    console.log("init cellstate");
    allTd = $(".cell");
    allTd.css("background-color", "transparent");
    allTd.unbind("click");
    if (graphicApi.invatedPosition) {
      console.log("mark invated cell");
      td = graphicApi.getCell(graphicApi.invatedPosition.x + 1, graphicApi.invatedPosition.y + 1);
      return td.css({
        "background-color": "rgba(100,256,256,0.5)"
      });
    }
  };

  graphicApi.flipBord = function(flip) {
    if (flip) {
      $("#boardImg").css({
        "transform": "rotate3d(0, 0, 1, 180deg)"
      });
    } else {
      $("#boardImg").css({
        "transform": "rotate3d(0, 0, 1, 0deg)"
      });
    }
    graphicApi.flip = flip;
    return graphicApi.redrawKoma(gameApi.game.board, gameApi.game.state, gameApi.game.turn);
  };

  graphicApi.getKomaImage = function(koma) {
    if (graphicApi.flip) {
      if (koma.playerNumber === 2) {
        return $("<img class='koma' src='./images/koma/60x64/" + images.koma1[koma.komaType] + "'>");
      } else {
        return $("<img class='koma' src='./images/koma/60x64/" + images.koma2[koma.komaType] + "'>");
      }
    } else {
      if (koma.playerNumber === 1) {
        return $("<img class='koma' src='./images/koma/60x64/" + images.koma1[koma.komaType] + "'>");
      } else {
        return $("<img class='koma' src='./images/koma/60x64/" + images.koma2[koma.komaType] + "'>");
      }
    }
  };

  graphicApi.getKomaDai = function(playerNumber) {
    if (graphicApi.flip) {
      return $('#komadai' + (playerNumber === 1 ? "2" : "1"));
    } else {
      return $('#komadai' + (playerNumber === 1 ? "1" : "2"));
    }
  };

  graphicApi.getGameInfoDiv = function(playerNumber) {
    if (graphicApi.flip) {
      return $('#gameInfo' + (playerNumber === 1 ? "2" : "1"));
    } else {
      return $('#gameInfo' + (playerNumber === 1 ? "1" : "2"));
    }
  };

  graphicApi.getPos = function(pos) {
    if (graphicApi.flip) {
      return 9 - pos;
    } else {
      return pos - 1;
    }
  };

  graphicApi.getCell = function(x, y) {
    if (graphicApi.flip) {
      return $("#cell_" + (10 - x) + "_" + (10 - y));
    } else {
      return $("#cell_" + x + "_" + y);
    }
  };

  graphicApi.hideModal = function() {
    $("#modal-window").hide();
    $("#modal-overlay").hide();
    if (graphicApi.afterHideModal) {
      graphicApi.afterHideModal();
      return graphicApi.afterHideModal = void 0;
    }
  };

  kifuApi.replayKifu = function(kifu) {
    var index, option, refresh;
    kifuApi.state = "replay";
    $('#kifuSelectBox').html("");
    $("#kifuInfoDiv").show();
    $("#kifuReplayDiv").show();
    refresh = function(index, board) {
      var kifuLength;
      graphicApi.updateGameInfo({
        player1: board.player1,
        player2: board.player2
      });
      $('#kifuSelectBox').val(index);
      kifuLength = $("#kifuSelectBox").children().length - 1;
      if (board.emphasisPosition) {
        graphicApi.invatedPosition = board.emphasisPosition;
      } else {
        graphicApi.invatedPosition = null;
      }
      graphicApi.redrawKoma(board, 1, "replay");
      $('#toStartButton').prop('disabled', index === 0);
      $('#backButton').prop('disabled', index === 0);
      $('#nextButton').prop('disabled', kifuLength === index);
      return $('#toEndButton').prop('disabled', kifuLength === index);
    };
    kifuApi.kifuPlayer = new KifuPlayer(kifu, 1, refresh);
    kifuApi.kifuPlayer.activateUpdateTimer();
    graphicApi.redrawKoma(kifuApi.kifuPlayer.getCurrentBoard(), 1, "replay");
    index = 0;
    $('#kifuSelectBox').unbind("change");
    $('#kifuSelectBox').bind("change", function() {
      index = $('#kifuSelectBox option:selected').val();
      return kifuApi.kifuPlayer.toIndex(parseInt(index));
    });
    option = $("<option value='" + index + "'>対局開始</option>");
    index++;
    $("#kifuSelectBox").append(option);
    return _(kifu).each(function(te) {
      var value;
      if (te.info.type === "moveKoma") {
        if (!te.foul) {
          value = ("" + te.turn + " : ") + (te.info.from.x + 1) + (te.info.from.y + 1) + (te.info.to.x + 1) + (te.info.to.y + 1) + te.info.koma;
        } else {
          value = ("" + te.turn + " : [反則] ") + (te.info.from.x + 1) + (te.info.from.y + 1) + (te.info.to.x + 1) + (te.info.to.y + 1) + te.info.koma;
        }
        option = $("<option value='" + index + "'>" + value + "</option>");
      } else if (te.info.type === "endGame") {
        value = "player" + te.info.winPlayerNumber + " win. (" + te.info.reason + ")";
        option = $("<option value='" + index + "'>" + value + "</option>");
      }
      index++;
      return $("#kifuSelectBox").append(option);
    });
  };

  kifuApi.addKifu = function(te) {
    var i, option, value;
    kifuApi.kifuPlayer.addKifu(te);
    i = $("#kifuSelectBox").children().length;
    if (te.info.type === "moveKoma") {
      if (!te.foul) {
        value = ("" + te.turn + " : ") + (te.info.from.x + 1) + (te.info.from.y + 1) + (te.info.to.x + 1) + (te.info.to.y + 1) + te.info.koma;
      } else {
        value = ("" + te.turn + " : [反則] ") + (te.info.from.x + 1) + (te.info.from.y + 1) + (te.info.to.x + 1) + (te.info.to.y + 1) + te.info.koma;
      }
      option = $("<option value='" + i + "'>" + value + "</option>");
    } else if (te.info.type === "endGame") {
      value = "player" + te.info.winPlayerNumber + " win. (" + te.info.reason + ")";
      option = $("<option value='" + i + "'>" + value + "</option>");
    }
    return $("#kifuSelectBox").append(option);
  };

  kifuApi.toStart = function() {
    return kifuApi.kifuPlayer.toStart();
  };

  kifuApi.next = function() {
    return kifuApi.kifuPlayer.next();
  };

  kifuApi.back = function() {
    return kifuApi.kifuPlayer.back();
  };

  kifuApi.toEnd = function() {
    return kifuApi.kifuPlayer.toEnd();
  };

  kifuApi.setElapsedTime = function(time) {
    return kifuApi.kifuPlayer.elapsedTime = time;
  };

  kifuApi.stop = function() {
    return kifuApi.state = "stop";
  };

}).call(this);
