// Generated by CoffeeScript 1.4.0
(function() {
  var canvas, images, loadImg;

  loadImg = function(filename) {
    var result;
    result = new Image();
    result.src = filename;
    return result;
  };

  images = [];

  images.hasami = loadImg("img/hasami.png");

  images.editor_cursor = loadImg("img/editor_cursor.png");

  images.floor_arrow_down = loadImg("img/floor_arrow_down.png");

  images.floor_arrow_left = loadImg("img/floor_arrow_left.png");

  images.floor_arrow_right = loadImg("img/floor_arrow_right.png");

  images.floor_arrow_up = loadImg("img/floor_arrow_up.png");

  images.floor_Ice = loadImg("img/floor_Ice.png");

  images.floor_net = loadImg("img/floor_net.png");

  images.floor_plain = loadImg("img/floor_plain.png");

  images.floor_step = loadImg("img/floor_step.png");

  canvas = document.getElementById('canvassample');

  ctx.drawImage(images.floor_plain, 32, 32);

  ctx.drawImage(images.hasami, 32, 32);

  ctx.drawImage(images.floor_arrow_down, 32, 64);

  ctx.drawImage(images.floor_Ice, 64, 32);

  ctx.drawImage(images.floor_plain, 64, 64);

  ctx.drawImage(images.floor_step, 32, 96);

}).call(this);
