// Generated by CoffeeScript 1.4.0
(function() {
  var TreeConnector;

  TreeConnector = (function() {

    function TreeConnector(parent) {
      var events;
      events = [];
      owner;

      this.addEvent = function(eventName, func) {
        return events[eventName] = func;
      };
      this.notice = function(eventName) {
        var _ref;
        if ((_ref = events[eventName]) != null) {
          _ref.apply(owner, [].slice(arguments, 1, arguments.length));
        }
        if (parent != null) {
          parent.notice.apply(parent, [].slice(arguments, 0, arguments.length));
        }
      };
      this.createChild = function() {
        return new TreeConnector(this);
      };
    }

    return TreeConnector;

  })();

}).call(this);
